import { parseFastq } from "../src/FASTQ";

import * as mocha from "mocha";
import * as chai from "chai";
const expect = chai.expect;

const SRR5364317: string[] = [
  "@SRR5364317.1 1 length=100",
  "CTCAAATTATAAAGATCATGATGAGAACAGCTGTTAGTGAAATAAATGATCCTATAGAAGAGACAGTGTTTCATGTGGTGTAAGCATCTGGGTAGTGAGA",
  "+SRR5364317.1 1 length=100",
  "/BBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
  "@SRR5364317.2 2 length=100",
  "GGCTCATACAATAAAGCCTAGAAAGCCAATAAACATTATTGCTCATACTATTCCTATATAGCCGAAAGGTTCTTTTTTTTCCGGAGTAGTAAGTAACTAC",
  "+SRR5364317.2 2 length=100",
  "/<<BBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
  "@SRR5364317.3 3 length=100",
  "CCCCGGGCTCCCAGGCCTGCTGAGGACCTCTCCAAGTCACAAGACCCCTGAGCTGTTGTTGCAGGGCACATCAGAACAGGGAGCTGGCTGAGCCCATCAC",
  "+SRR5364317.3 3 length=100",
  "/</BBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF<FFFF",
  "@SRR5364317.4 4 length=100",
  "CTCCTCTGAGGATTTTAAAGAAGCCATTATCACCCCAGTCAAGGTTCCAAGAGTTGGCTGCCAGCCAGTAGGGAACTCCATTCTCTACTCCCCAGCCCAG",
  "+SRR5364317.4 4 length=100",
  "<BBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
  "@SRR5364317.5 5 length=100",
  "CTCGTTTCCAGGAAAGTGACATAGTAGGTGCACAGTCACCTGGTTGCTGCAATAATGTTCCAATTCCTGCTGCTTGAAAAAGGGAGCCATCATGTTCCAT",
  "+SRR5364317.5 5 length=100",
  "BBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
  "@SRR5364317.6 6 length=100",
  "CAGAACAATTGGTAAAGAACTGTTTAGCACGCATGAAAATTTAAATTCAACCCCAGGACAGGATAAGCAGGGCATGGGGACACTCTCCTGCTGTCCCAGC",
  "+SRR5364317.6 6 length=100",
  "</<BBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF<FFFFBFFFFFFFFFFFFF",
  "@SRR5364317.7 7 length=100",
  "CATGAGGAAGGATGCCCCAAAGAAGGATGGCGGTTTCCGTTTGACCAGTCGGAACGCGTTGGGGATAACAGCTGACAGCAGAGTGGTGTGGATGTCGCCC",
  "+SRR5364317.7 7 length=100",
  "/<<BBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFF",
  "@SRR5364317.8 8 length=100",
  "CTTGAGTTCACCTTCATTGACTTCATCGTTCTCTCTGTCCACCTGGGCCTTCAGCACGTATCTCTTTATGAGCCGCTTCATGATCTTCTGCTACCTGGTG",
  "+SRR5364317.8 8 length=100",
  "BB/BBBF<F<FFFFFFFFFFFFFFFFFFFFFFFFFB<FFB/FFFFBFFF//<</</B/B/<FFF/BB/FFF/FF/B<FF///</FBFFF//<</<<BB<B",
  "@SRR5364317.9 9 length=100",
  "AAATAACAAGGCTCCGCCAAAGAGAAACCAACTATTGGTGTGAAAATTTTCTTTAAAGGTTTTAAAGAAGTCAACATAATAGGTCACAACGATGGATGCC",
  "+SRR5364317.9 9 length=100",
  "BBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFF",
  "@SRR5364317.10 10 length=100",
  "GTTTGGCCATCCCTCTGCTCAGACAATATCTAGCCCCCATGTCTCCAGCAGCACCCTGTGACTGTGTGGTCAATTGCAGTGAACCTGGCCTCTCTCTGGA",
  "+SRR5364317.10 10 length=100",
  "/BBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBF",
  "@SRR5364317.11 11 length=100",
  "TTTACTCCTACGAATATGATGGCGAAGTGGGCTTTTGCTCATGTGTCATCTAGGGTGAAGCCTGAAAATAATGGGAATCAGTGAACAAATCCTGCTATGA",
  "+SRR5364317.11 11 length=100",
  "/BBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
  "@SRR5364317.12 12 length=100",
  "CTCAATGTCGATGAGAAGCATGACCTGCTCCTTGGTGCGGCCCTCACGTTCCCGGATGTGGGTGGTCACAATTCGCTCCATCTCCTCCCGCAGACGCGGG",
  "+SRR5364317.12 12 length=100",
  "/BBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFF/FFFFFFFFFFFFF<FFFFFF",
  "@SRR5364317.13 13 length=100",
  "GGGGATGCCGGAGATGACATTGGGCTGGATGAACTCAAGCTTGTCTACAAACTCTGCAGAGGCCCCTGGGAACTGGGGCTTGTCGTCCAGGGATGGGAAC",
  "+SRR5364317.13 13 length=100",
  "/<<BBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
];

describe("simple fastq parsing", () => {
  it("empty", () => {
    const none: string[] = [];
    const entries = [...parseFastq(none.values())];
    expect(entries.length).to.equal(0);
  });
  it("SRR5364317", () => {
    const entries = [...parseFastq(SRR5364317.values())];
    expect(entries.length).to.equal(13);
    expect(entries[12][0]).to.eql("@SRR5364317.13 13 length=100");
  });
  it("SRR5364317 (truncated)", () => {
    const truncated = SRR5364317.slice(0, 6);
    expect(() => [...parseFastq(truncated.values())].length).to.throw(Error, "last FASTQ read is incomplete (line 6)");
  });
});
